fixed actions

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -31,85 +31,86 @@ inputs:
     required: true
     default: ${{ github.workspace }}/extras/test/build/coverage.info
 
-runs:
-  using: composite
-  steps:
-    - name: Build tests
-      shell: bash
-      run: |
-        echo "::group::Run CMake on ${{ inputs.source-path }}"
-        cmake -S "${{ inputs.source-path }}" -B "${{ inputs.build-path }}"
-        echo "::endgroup::"
-        echo "::group::Run Make on ${{ inputs.build-path }}"
-        make --directory="${{ inputs.build-path }}"
-        echo "::endgroup::"
-
-    - name: Install yq
-      shell: bash
-      run: |
-        sudo snap install yq > /dev/null
-
-    - name: Update APT package lists
-      shell: bash
-      run: |
-        sudo apt-get update > /dev/null
-
-    - name: Install Valgrind
-      shell: bash
-      run: |
-        sudo apt-get --assume-yes install valgrind > /dev/null
-
-    - name: Run tests
-      shell: bash
-      run: |
-        if [[ -n "${{ inputs.runtime-path }}" ]]; then
-          echo "::warning::The runtime-path input is deprecated. Please use runtime-paths instead."
-          RUNTIME_PATHS="- ${{ inputs.runtime-path }}"
-        else
-          RUNTIME_PATHS="${{ inputs.runtime-paths }}"
-        fi
-
-        EXIT_STATUS=0
-        set +o errexit
-        while IFS='' read -r runtimePath && [[ -n "$runtimePath" ]]; do
-          echo "::group::Run $runtimePath with Valgrind"
-          if ! valgrind --tool=memcheck --leak-check=yes --error-exitcode=1 "$runtimePath"; then
-            EXIT_STATUS=1
-            echo "::error file=$runtimePath::While running $runtimePath"
-          fi
+jobs:
+  build-and-test:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Build tests
+        shell: bash
+        run: |
+          echo "::group::Run CMake on ${{ inputs.source-path }}"
+          cmake -S "${{ inputs.source-path }}" -B "${{ inputs.build-path }}"
           echo "::endgroup::"
-        done <<<"$(echo "$RUNTIME_PATHS" | yq eval '.[]' -)"
-        exit $EXIT_STATUS
+          echo "::group::Run Make on ${{ inputs.build-path }}"
+          make --directory="${{ inputs.build-path }}"
+          echo "::endgroup::"
 
-    - name: Parse coverage-exclude-paths input
-      id: parse-coverage-exclude-paths
-      shell: bash
-      run: |
-        while IFS='' read -r excludePath && [[ -n "$excludePath" ]]; do
-          excludePaths="$excludePaths $excludePath"
-        done <<<"$(echo "${{ inputs.coverage-exclude-paths }}" | yq eval '.[]' -)"
-        # Make the parsed paths an output so it can be used by the next step
-        echo "::set-output name=paths::$excludePaths"
+      - name: Install yq
+        shell: bash
+        run: |
+          sudo snap install yq > /dev/null
 
-    - name: Install LCOV
-      shell: bash
-      run: |
-        sudo apt-get --assume-yes install lcov > /dev/null
+      - name: Update APT package lists
+        shell: bash
+        run: |
+          sudo apt-get update > /dev/null
 
-    - name: Generate code coverage data
-      shell: bash
-      run: |
-        echo "::group::Generate code coverage data from ${{ inputs.build-path }}"
-        mkdir --parents "$(dirname -- "${{ inputs.coverage-data-path }}")"
-        lcov --directory "${{ inputs.build-path }}" --capture --output-file "${{ inputs.coverage-data-path }}"
-        set -o noglob
-        lcov --quiet --remove "${{ inputs.coverage-data-path }}" ${{ steps.parse-coverage-exclude-paths.outputs.paths }} --output-file "${{ inputs.coverage-data-path }}"
-        set +o noglob
-        echo "::endgroup::"
+      - name: Install Valgrind
+        shell: bash
+        run: |
+          sudo apt-get --assume-yes install valgrind > /dev/null
 
-    - name: Display coverage report in log
-      shell: bash
-      run: |
-        echo "::group::Report code coverage"
-        lcov --list "${{ inputs.coverage-data-path }}"
-        echo "::endgroup::"
+      - name: Run tests
+        shell: bash
+        run: |
+          if [[ -n "${{ inputs.runtime-path }}" ]]; then
+            echo "::warning::The runtime-path input is deprecated. Please use runtime-paths instead."
+            RUNTIME_PATHS="- ${{ inputs.runtime-path }}"
+          else
+            RUNTIME_PATHS="${{ inputs.runtime-paths }}"
+          fi
+
+          EXIT_STATUS=0
+          set +o errexit
+          while IFS='' read -r runtimePath && [[ -n "$runtimePath" ]]; do
+            echo "::group::Run $runtimePath with Valgrind"
+            if ! valgrind --tool=memcheck --leak-check=yes --error-exitcode=1 "$runtimePath"; then
+              EXIT_STATUS=1
+              echo "::error file=$runtimePath::While running $runtimePath"
+            fi
+            echo "::endgroup::"
+          done <<<"$(echo "$RUNTIME_PATHS" | yq eval '.[]' -)"
+          exit $EXIT_STATUS
+
+      - name: Parse coverage-exclude-paths input
+        id: parse-coverage-exclude-paths
+        shell: bash
+        run: |
+          while IFS='' read -r excludePath && [[ -n "$excludePath" ]]; do
+            excludePaths="$excludePaths $excludePath"
+          done <<<"$(echo "${{ inputs.coverage-exclude-paths }}" | yq eval '.[]' -)"
+          # Make the parsed paths an output so it can be used by the next step
+          echo "::set-output name=paths::$excludePaths"
+
+      - name: Install LCOV
+        shell: bash
+        run: |
+          sudo apt-get --assume-yes install lcov > /dev/null
+
+      - name: Generate code coverage data
+        shell: bash
+        run: |
+          echo "::group::Generate code coverage data from ${{ inputs.build-path }}"
+          mkdir --parents "$(dirname -- "${{ inputs.coverage-data-path }}")"
+          lcov --directory "${{ inputs.build-path }}" --capture --output-file "${{ inputs.coverage-data-path }}"
+          set -o noglob
+          lcov --quiet --remove "${{ inputs.coverage-data-path }}" ${{ steps.parse-coverage-exclude-paths.outputs.paths }} --output-file "${{ inputs.coverage-data-path }}"
+          set +o noglob
+          echo "::endgroup::"
+
+      - name: Display coverage report in log
+        shell: bash
+        run: |
+          echo "::group::Report code coverage"
+          lcov --list "${{ inputs.coverage-data-path }}"
+          echo "::endgroup::"
